Avoid import conflicts with tests folder in dist-packages (#22710)
Why I did it
We observed that a folder named tests exists at the path /usr/local/lib/python3.8/dist-packages, which conflicts with the tests directory in the sonic-mgmt codebase. When attempting to import modules from tests.common within sonic-mgmt (e.g., from the ansible directory), Python mistakenly resolves the import to /usr/local/lib/python3.8/dist-packages/tests/, resulting in the following error:

ModuleNotFoundError: No module named 'tests.common'
This issue stems from the msal-extension package, which includes a tests folder that gets installed into dist-packages. Although version 1.3.1 of msal-extension resolves this problem, we are currently unable to upgrade to that version due to Python version constraints.

As a temporary workaround, we manually remove the tests directory from dist-packages after the build process. This can be reverted once the Python version used in the sonic-mgmt Docker environment is upgraded and we are able to adopt a newer version of msal-extension.

Work item tracking
Microsoft ADO (number only):
How I did it
Manually removed the tests folder from the dist-packages directory after the build process.

How to verify it
Use the newly build image to set up a container, and we can see that there is no tests folder under path /usr/local/lib/python3.8/dist-packages/tests/
image