[docker-ptf]: TACACS fix, Python 3.9 deprecation fixes and build updates (#21451)
Why I did it
With tacacs+ built manually for PY3 only image the directory /etc/tacacs+ and /etc/default/tacacs+ are missing causing tests to fail.
The most recent changes to pip packages throws errors related to Python 3.9 deprecations like -

from distutils.command.build_py import build_py_2to3 as _build_py - Python 3.9 does not have build_py_2to3 anymore.
AttributeError: 'HTMLParser' object has no attribute 'unescape' when installing packages like nnpy, ipython etc. - Fixed by using virtualenv instead.
These errors are because some packages downgrade setuptools causing subsequent package installs to fail.

Work item tracking
Microsoft ADO (number only): 29869339
How I did it
Update Dockerfile for docker-ptf only where it is applicable to "py3".

How to verify it
Build and ran tests

Which release branch to backport (provide reason below if selected)
 201811
 201911
 202006
 202012
 202106
 202111
 202205
 202211
 202305

Tested branch (Please provide the tested image version)
Not applicable. The image is not built on any branch yet. The flag is turned off by default.

Description for the changelog
[docker-ptf]: TACACS fix, Python 3.9 deprecation fixes and build updates

With tacacs+ built manually for PY3 only image the directory /etc/tacacs+ and /etc/default/tacacs+ are missing causing tests to fail.
The most recent changes to pip packages throws errors related to Python 3.9 deprecations like -

from distutils.command.build_py import build_py_2to3 as _build_py - Python 3.9 does not have build_py_2to3 anymore.
AttributeError: 'HTMLParser' object has no attribute 'unescape' when installing packages like nnpy, ipython etc. - Fixed by using virtualenv instead.
These errors are because some packages downgrade setuptools causing subsequent package installs to fail.

Link to config_db schema for YANG module changes
Not applicable